name: fairf
description: FairF - a 2D competitive room-based shooter (1v1 / 2v2)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  cupertino_icons: ^1.0.6
  model_viewer_plus: ^1.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/characters/
    - assets/characters_3d/
